name: Godot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        godot_version: ["4.5"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Godot CI
        uses: abarichello/godot-ci@4.5-stable
        with:
          godot_version: ${{ matrix.godot_version }}
          export_presets: "export_presets.cfg"
          run_tests: "true"
          cache: "true"