name: Godot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  EXPORT_NAME: gdt_sndbx
jobs:
  web-build:
    name: Web Build and Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    container: 
      image: witchpixels/godot4-omnibuilder3d:latest-4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Fix paths for Github
        run: setup_github_paths.sh
      - name: Install Blender
        run: install_blender.sh 4.5.3
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd src
          godot --headless --verbose --export-release "Web" "../build/web/$EXPORT_NAME/index.html"
          cd ..
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.